on:
  rss:
    url: https://www.sakrum.de/feeds/posts/default?alt=rss
    config:
      every: "0 10 * * *"
      limit: 5
      filter:
        content:
            $regex: ....+
        title:
            $not:
              $regex: (Evangelium|Kommentar|Psalm)
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{on.rss.outputs.title}} 👉🏻${{on.rss.outputs.link}}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
  mastodon:
    name: post2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: send to muncih
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.MASTODON_POST_URL }}
          method: 'POST'
          content-type: application/x-www-form-urlencoded
          data: 'visibility=unlisted&status=${{on.rss.outputs.title}} 👉🏻${{on.rss.outputs.link}}'
          timeout: 10000
          is_debug: false
  mastodon2:
    name: post2mastodon2
    runs-on: ubuntu-latest
    steps:
      - name: send to bayern
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.MASTODON_POST_URL_2 }}
          method: 'POST'
          content-type: application/x-www-form-urlencoded
          data: 'visibility=unlisted&status=${{on.rss.outputs.title}} 👉🏻${{on.rss.outputs.link}}'
          timeout: 10000
          is_debug: false          
#   friendica:
#     name: post2friendica
#     runs-on: ubuntu-latest
#     steps:
#       - name: send to friendica
#         uses: actionsflow/axios@v1
#         with:
#           url: ${{ secrets.FRIENDICA_POST_URL }}
#           method: 'POST'
#           accept: 200,201,204
#           content-type: application/x-www-form-urlencoded
#           data: 'key=${{ secrets.FRIENDICA_KEY }}&type=link&link=<<<${{on.rss.outputs.link}}>>>&title=<<<${{on.rss.outputs.title}}>>>&msg=<<<${{on.rss.outputs.content}}>>>&description=<<<${{on.rss.outputs.contentSnippet}}>>>&date=<<<${{on.rss.outputs.pubDate}}>>>&url=<<<${{on.rss.outputs.link}}>>>'
#           timeout: 10000
#           is_debug: false
